<?php
$productos = [
    // HOMBRE - CAMISAS
    [
        'id' => '001',
        'nombre' => 'Camisa Clásica Negra',
        'descripcion_corta' => 'Camisa negra de algodón. Estilo formal-elegante.',
        'descripcion' => 'Camisa en tono negro con corte regular fit. Manga larga y cuello italiano. Ideal para eventos formales y oficina.',
        'precio' => 450,
        'stock' => 12,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/001_camisa-clasica_negra.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#000000'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '002',
        'nombre' => 'Camisa Clásica Blanca',
        'descripcion_corta' => 'Camisa blanca de algodón. Básica y versátil.',
        'descripcion' => 'Camisa en tono blanco con corte regular fit. Manga larga y cuello italiano. La más básica, combina con todo.',
        'precio' => 450,
        'stock' => 15,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/002_camisa-clasica_blanca.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#FFFFFF'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '003',
        'nombre' => 'Camisa Clásica Azul',
        'descripcion_corta' => 'Camisa azul cielo de algodón. Estilo casual-elegante.',
        'descripcion' => 'Camisa en tono azul cielo con corte regular fit. Manga larga y cuello italiano. Versátil para combinar con jeans o pantalón de vestir.',
        'precio' => 450,
        'stock' => 6,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/003_camisa-clasica_azul.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#4A90E2'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '004',
        'nombre' => 'Camisa Clásica Gris',
        'descripcion_corta' => 'Camisa gris oxford de algodón. Estilo ejecutivo.',
        'descripcion' => 'Camisa en tono gris oxford con corte regular fit. Manga larga y cuello italiano. Tono neutro muy elegante para oficina.',
        'precio' => 450,
        'stock' => 9,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/004_camisa-clasica_gris.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#808080'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '005',
        'nombre' => 'Camisa Clásica Celeste',
        'descripcion_corta' => 'Camisa celeste de algodón. Fresca y elegante.',
        'descripcion' => 'Camisa en tono celeste con corte regular fit. Manga larga y cuello italiano. Ideal para clima cálido de La Paz.',
        'precio' => 450,
        'stock' => 8,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/005_camisa-clasica_celeste.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#87CEEB'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '006',
        'nombre' => 'Camisa Clásica Beige',
        'descripcion_corta' => 'Camisa beige de algodón. Casual elegante.',
        'descripcion' => 'Camisa en tono beige con corte regular fit. Manga larga y cuello italiano. Tono tierra perfecto para look casual elegante.',
        'precio' => 450,
        'stock' => 7,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/006_camisa-clasica_beige.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#F5F5DC'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '007',
        'nombre' => 'Camisa Clásica Verde',
        'descripcion_corta' => 'Camisa verde olivo de algodón. Moderna y diferente.',
        'descripcion' => 'Camisa en tono verde olivo con corte regular fit. Manga larga y cuello italiano. Color moderno para destacar sin perder formalidad.',
        'precio' => 450,
        'stock' => 6,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/007_camisa-clasica_verde.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#556B2F'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => true
    ],
    [
        'id' => '008',
        'nombre' => 'Camisa Clásica Vino',
        'descripcion_corta' => 'Camisa vino tinto de algodón. Elegante y sofisticada.',
        'descripcion' => 'Camisa en tono vino tinto con corte regular fit. Manga larga y cuello italiano. Perfecta para eventos nocturnos y cenas.',
        'precio' => 450,
        'stock' => 8,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/008_camisa-clasica_vino.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#722F37'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => true
    ],
    [
        'id' => '009',
        'nombre' => 'Camisa Clásica Café',
        'descripcion_corta' => 'Camisa café de algodón. Tono cálido y combinable.',
        'descripcion' => 'Camisa en tono café con corte regular fit. Manga larga y cuello italiano. Tono cálido muy combinable para otoño-invierno.',
        'precio' => 450,
        'stock' => 5,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/009_camisa-clasica_cafe.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#6F4E37'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => false
    ],
    [
        'id' => '010',
        'nombre' => 'Camisa Clásica Lila',
        'descripcion_corta' => 'Camisa lila suave de algodón. Moderna y elegante.',
        'descripcion' => 'Camisa en tono lila suave con corte regular fit. Manga larga y cuello italiano. Color moderno y elegante para oficina o eventos.',
        'precio' => 450,
        'stock' => 6,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/camisas/010_camisa-clasica_lila.jpg',
        'cat' => 'hombre',
        'sub' => 'camisas',
        'tallas' => ['U', 'CH', 'M', 'G', 'XG'],
        'colores' => ['#C8A2C8'],
        'material' => 'Algodón 95% Poliéster 5%',
        'nuevo' => true
    ],
    // HOMBRE - PANTALONES
    [
        'id' => '011',
        'nombre' => 'Pantalón Vaquero 501 Azul Clásico',
        'descripcion_corta' => 'Mezclilla azul clásica corte 501. Recto y atemporal.',
        'descripcion' => 'Pantalón de mezclilla azul clásico con corte 501 recto. Tiro medio, pierna recta. 4 bolsillos. El original que nunca pasa de moda.',
        'precio' => 650,
        'stock' => 10,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/pantalones/011_pantalon-501_azul-clasico.jpg',
        'cat' => 'hombre',
        'sub' => 'pantalones',
        'tallas' => ['28', '30', '32', '34', '36', '38'],
        'colores' => ['#1E3A5F'],
        'material' => 'Mezclilla 100% algodón',
        'nuevo' => false
    ],
    [
        'id' => '012',
        'nombre' => 'Pantalón Vaquero 501 Negro',
        'descripcion_corta' => 'Mezclilla negra corte 501. Elegante y combinable.',
        'descripcion' => 'Pantalón de mezclilla negra con corte 501 recto. Tiro medio, pierna recta. 4 bolsillos. Perfecto para look casual elegante.',
        'precio' => 650,
        'stock' => 8,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/pantalones/012_pantalon-501_negro.jpg',
        'cat' => 'hombre',
        'sub' => 'pantalones',
        'tallas' => ['28', '30', '32', '34', '36', '38'],
        'colores' => ['#000000'],
        'material' => 'Mezclilla 100% algodón',
        'nuevo' => false
    ],
    [
        'id' => '020',
        'nombre' => 'Pantalón Vaquero 501 Café',
        'descripcion_corta' => 'Mezclilla café corte 501. Cálido y clásico.',
        'descripcion' => 'Pantalón de mezclilla café con corte 501 recto. Tiro medio, pierna recta. Tono cálido muy combinable para otoño-invierno.',
        'precio' => 650,
        'stock' => 6,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/pantalones/020_pantalon-501_cafe.jpg',
        'cat' => 'hombre',
        'sub' => 'pantalones',
        'tallas' => ['28', '30', '32', '34', '36', '38'],
        'colores' => ['#6F4E37'],
        'material' => 'Mezclilla 100% algodón',
        'nuevo' => false
    ],
    // HOMBRE - BOXER
    [
        'id' => '013',
        'nombre' => 'Boxer Deportivo',
        'descripcion_corta' => 'Boxer transpirable para actividad física. Ajuste perfecto.',
        'descripcion' => 'Boxer deportivo con tecnología dry-fit que absorbe la humedad. Elástico ancho y cómodo. Sin costuras molestas. Ideal para entrenar.',
        'precio' => 180,
        'stock' => 8,
        'img' => 'https://m.media-amazon.com/images/I/71h3b9wFP4L._UY1000_.jpg',
        'cat' => 'hombre',
        'sub' => 'boxer',
        'tallas' => ['CH', 'M', 'G', 'XG'],
        'colores' => ['#000000', '#1E3A5F'],
        'material' => 'Poliéster 90% Elastano 10%',
        'nuevo' => false
    ],
    // HOMBRE - SUDADERA
    [
        'id' => '019',
        'nombre' => 'Sudadera Negra',
        'descripcion_corta' => 'Sudadera negra con capucha. Estilo urbano y cómoda.',
        'descripcion' => 'Sudadera negra de algodón con capucha ajustable y bolsillo canguro. Corte regular. Perfecta para clima fresco.',
        'precio' => 450,
        'stock' => 15,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/hombre/sudaderas/sudadera-negra.jpg',
        'cat' => 'hombre',
        'sub' => 'sudadera',
        'tallas' => ['CH', 'M', 'G', 'XG'],
        'colores' => ['#000000'],
        'material' => 'Algodón 100%',
        'nuevo' => true
    ],
    // MUJER
    [
        'id' => '014',
        'nombre' => 'Blusa Casual',
        'descripcion_corta' => 'Blusa holgada de manga 3/4. Estilo fresco y cómodo.',
        'descripcion' => 'Blusa de corte holgado con escote en V y manga 3/4. Tela ligera y fresca. Perfecta para clima cálido o uso diario casual.',
        'precio' => 550,
        'stock' => 3,
        'img' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT5zB--Ln5Hb9-2xq9VVbYv0sUSBLaturC5AHc5hZ2MeFPM9_mh3me0EwpH5tT8mOeQBTQlgTL88rekvHuZSr4XaTtG_neC1V7EblmtvKIC3h9-p2W9wD7lteKRbkieE2GZ3ufkwec&usqp=CAc',
        'cat' => 'mujer',
        'sub' => 'blusas',
        'tallas' => ['CH', 'M', 'G', 'XG'],
        'colores' => ['#E8B4B8'],
        'material' => 'Rayón 100%',
        'nuevo' => false
    ],
    [
        'id' => '021',
        'nombre' => 'Short Casual',
        'descripcion_corta' => 'Short casual de algodón. Perfecto para verano.',
        'descripcion' => 'Short casual de algodón con elástico en cintura. Corte regular. Bolsillos laterales. Ideal para verano en La Paz.',
        'precio' => 350,
        'stock' => 20,
        'img' => '/NOVEDADES_ECONOMICA/img/productos/mujer/shorts/short-casual.jpg',
        'cat' => 'mujer',
        'sub' => 'shorts',
        'tallas' => ['CH', 'M', 'G', 'XG'],
        'colores' => ['#87CEEB'],
        'material' => 'Algodón 100%',
        'nuevo' => true
    ],
    [
        'id' => '015',
        'nombre' => 'Vestido Floral',
        'descripcion_corta' => 'Vestido midi con estampado floral. Fresco y femenino.',
        'descripcion' => 'Vestido midi con estampado floral y manga corta. Corte en A que favorece la silueta. Cierre lateral. Ideal para eventos de día o salidas casuales.',
        'precio' => 780,
        'stock' => 2,
        'img' => 'https://m.media-amazon.com/images/I/71s4h8h0l-L._UY1000_.jpg',
        'cat' => 'mujer',
        'sub' => 'vestidos',
        'tallas' => ['CH', 'M', 'G'],
        'colores' => ['#FF6B9D'],
        'material' => 'Poliéster 100%',
        'nuevo' => true
    ]
];
?>